// Code generated by protoc-gen-go.
// source: userinfo.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	userinfo.proto

It has these top-level messages:
	GetUserInfoRes
	GetMemberDetailReq
	BatchGetMemberCustomReq
	GetMemberCustomResp
	BatchGetMemberCustomResp
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetUserInfoRes struct {
	Result     int32  `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	Uid        uint32 `protobuf:"varint,2,opt,name=uid" json:"uid,omitempty"`
	Nn         string `protobuf:"bytes,3,opt,name=nn" json:"nn,omitempty"`
	Un         string `protobuf:"bytes,4,opt,name=un" json:"un,omitempty"`
	Gid        int32  `protobuf:"varint,5,opt,name=gid" json:"gid,omitempty"`
	Orm        int32  `protobuf:"varint,6,opt,name=orm" json:"orm,omitempty"`
	Ems        int32  `protobuf:"varint,7,opt,name=ems" json:"ems,omitempty"`
	Po         string `protobuf:"bytes,8,opt,name=po" json:"po,omitempty"`
	Pos        int32  `protobuf:"varint,9,opt,name=pos" json:"pos,omitempty"`
	It         int32  `protobuf:"varint,10,opt,name=it" json:"it,omitempty"`
	Its        int32  `protobuf:"varint,11,opt,name=its" json:"its,omitempty"`
	Sex        int32  `protobuf:"varint,12,opt,name=sex" json:"sex,omitempty"`
	Icon       string `protobuf:"bytes,13,opt,name=icon" json:"icon,omitempty"`
	Rip        string `protobuf:"bytes,14,opt,name=rip" json:"rip,omitempty"`
	Rsrc       string `protobuf:"bytes,15,opt,name=rsrc" json:"rsrc,omitempty"`
	Rt         uint64 `protobuf:"varint,16,opt,name=rt" json:"rt,omitempty"`
	Cid        int32  `protobuf:"varint,17,opt,name=cid" json:"cid,omitempty"`
	Qq         string `protobuf:"bytes,18,opt,name=qq" json:"qq,omitempty"`
	UpdateTime uint64 `protobuf:"varint,19,opt,name=update_time,json=updateTime" json:"update_time,omitempty"`
}

func (m *GetUserInfoRes) Reset()                    { *m = GetUserInfoRes{} }
func (m *GetUserInfoRes) String() string            { return proto.CompactTextString(m) }
func (*GetUserInfoRes) ProtoMessage()               {}
func (*GetUserInfoRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetUserInfoRes) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *GetUserInfoRes) GetUid() uint32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *GetUserInfoRes) GetNn() string {
	if m != nil {
		return m.Nn
	}
	return ""
}

func (m *GetUserInfoRes) GetUn() string {
	if m != nil {
		return m.Un
	}
	return ""
}

func (m *GetUserInfoRes) GetGid() int32 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func (m *GetUserInfoRes) GetOrm() int32 {
	if m != nil {
		return m.Orm
	}
	return 0
}

func (m *GetUserInfoRes) GetEms() int32 {
	if m != nil {
		return m.Ems
	}
	return 0
}

func (m *GetUserInfoRes) GetPo() string {
	if m != nil {
		return m.Po
	}
	return ""
}

func (m *GetUserInfoRes) GetPos() int32 {
	if m != nil {
		return m.Pos
	}
	return 0
}

func (m *GetUserInfoRes) GetIt() int32 {
	if m != nil {
		return m.It
	}
	return 0
}

func (m *GetUserInfoRes) GetIts() int32 {
	if m != nil {
		return m.Its
	}
	return 0
}

func (m *GetUserInfoRes) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *GetUserInfoRes) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *GetUserInfoRes) GetRip() string {
	if m != nil {
		return m.Rip
	}
	return ""
}

func (m *GetUserInfoRes) GetRsrc() string {
	if m != nil {
		return m.Rsrc
	}
	return ""
}

func (m *GetUserInfoRes) GetRt() uint64 {
	if m != nil {
		return m.Rt
	}
	return 0
}

func (m *GetUserInfoRes) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *GetUserInfoRes) GetQq() string {
	if m != nil {
		return m.Qq
	}
	return ""
}

func (m *GetUserInfoRes) GetUpdateTime() uint64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

type GetMemberDetailReq struct {
	Uid      uint32 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Nickname string `protobuf:"bytes,2,opt,name=nickname" json:"nickname,omitempty"`
	UserName string `protobuf:"bytes,3,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	Email    string `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
	Phone    string `protobuf:"bytes,5,opt,name=phone" json:"phone,omitempty"`
}

func (m *GetMemberDetailReq) Reset()                    { *m = GetMemberDetailReq{} }
func (m *GetMemberDetailReq) String() string            { return proto.CompactTextString(m) }
func (*GetMemberDetailReq) ProtoMessage()               {}
func (*GetMemberDetailReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetMemberDetailReq) GetUid() uint32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *GetMemberDetailReq) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *GetMemberDetailReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *GetMemberDetailReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetMemberDetailReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type BatchGetMemberCustomReq struct {
	UserInfoMask uint64                `protobuf:"varint,1,opt,name=user_info_mask,json=userInfoMask" json:"user_info_mask,omitempty"`
	ReqList      []*GetMemberDetailReq `protobuf:"bytes,2,rep,name=req_list,json=reqList" json:"req_list,omitempty"`
}

func (m *BatchGetMemberCustomReq) Reset()                    { *m = BatchGetMemberCustomReq{} }
func (m *BatchGetMemberCustomReq) String() string            { return proto.CompactTextString(m) }
func (*BatchGetMemberCustomReq) ProtoMessage()               {}
func (*BatchGetMemberCustomReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *BatchGetMemberCustomReq) GetUserInfoMask() uint64 {
	if m != nil {
		return m.UserInfoMask
	}
	return 0
}

func (m *BatchGetMemberCustomReq) GetReqList() []*GetMemberDetailReq {
	if m != nil {
		return m.ReqList
	}
	return nil
}

type GetMemberCustomResp struct {
	Result      int32  `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	Uid         uint32 `protobuf:"varint,2,opt,name=uid" json:"uid,omitempty"`
	Nickname    string `protobuf:"bytes,3,opt,name=nickname,json=nn" json:"nickname,omitempty"`
	Username    string `protobuf:"bytes,4,opt,name=username,json=un" json:"username,omitempty"`
	GroupId     int32  `protobuf:"varint,5,opt,name=group_id,json=gid" json:"group_id,omitempty"`
	OwnRoom     int32  `protobuf:"varint,6,opt,name=own_room,json=orm" json:"own_room,omitempty"`
	Email       string `protobuf:"bytes,7,opt,name=email,json=em" json:"email,omitempty"`
	EmailStatus int32  `protobuf:"varint,8,opt,name=email_status,json=ems" json:"email_status,omitempty"`
	Phone       string `protobuf:"bytes,9,opt,name=phone,json=po" json:"phone,omitempty"`
	PhoneStatus int32  `protobuf:"varint,10,opt,name=phone_status,json=pos" json:"phone_status,omitempty"`
	IdentType   int32  `protobuf:"varint,11,opt,name=ident_type,json=it" json:"ident_type,omitempty"`
	IdentStatus int32  `protobuf:"varint,12,opt,name=ident_status,json=its" json:"ident_status,omitempty"`
	Sex         int32  `protobuf:"varint,13,opt,name=sex" json:"sex,omitempty"`
	Icon        string `protobuf:"bytes,14,opt,name=icon" json:"icon,omitempty"`
	RegIp       string `protobuf:"bytes,15,opt,name=reg_ip,json=rip" json:"reg_ip,omitempty"`
	RegSrc      string `protobuf:"bytes,16,opt,name=reg_src,json=rsrc" json:"reg_src,omitempty"`
	RegTime     int32  `protobuf:"varint,17,opt,name=reg_time,json=rt" json:"reg_time,omitempty"`
	CpsId       int32  `protobuf:"varint,18,opt,name=cps_id,json=cid" json:"cps_id,omitempty"`
	Qq          string `protobuf:"bytes,19,opt,name=qq" json:"qq,omitempty"`
	Nation      string `protobuf:"bytes,20,opt,name=nation,json=n" json:"nation,omitempty"`
	Province    string `protobuf:"bytes,21,opt,name=province,json=p" json:"province,omitempty"`
	City        string `protobuf:"bytes,22,opt,name=city,json=c" json:"city,omitempty"`
	UpdateTime  int32  `protobuf:"varint,23,opt,name=update_time,json=ut" json:"update_time,omitempty"`
	Password    string `protobuf:"bytes,24,opt,name=password,json=pass" json:"password,omitempty"`
	Salt        string `protobuf:"bytes,25,opt,name=salt,json=s" json:"salt,omitempty"`
	Seq         int32  `protobuf:"varint,26,opt,name=seq" json:"seq,omitempty"`
}

func (m *GetMemberCustomResp) Reset()                    { *m = GetMemberCustomResp{} }
func (m *GetMemberCustomResp) String() string            { return proto.CompactTextString(m) }
func (*GetMemberCustomResp) ProtoMessage()               {}
func (*GetMemberCustomResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetMemberCustomResp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *GetMemberCustomResp) GetUid() uint32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *GetMemberCustomResp) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *GetMemberCustomResp) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetMemberCustomResp) GetGroupId() int32 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *GetMemberCustomResp) GetOwnRoom() int32 {
	if m != nil {
		return m.OwnRoom
	}
	return 0
}

func (m *GetMemberCustomResp) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetMemberCustomResp) GetEmailStatus() int32 {
	if m != nil {
		return m.EmailStatus
	}
	return 0
}

func (m *GetMemberCustomResp) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *GetMemberCustomResp) GetPhoneStatus() int32 {
	if m != nil {
		return m.PhoneStatus
	}
	return 0
}

func (m *GetMemberCustomResp) GetIdentType() int32 {
	if m != nil {
		return m.IdentType
	}
	return 0
}

func (m *GetMemberCustomResp) GetIdentStatus() int32 {
	if m != nil {
		return m.IdentStatus
	}
	return 0
}

func (m *GetMemberCustomResp) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *GetMemberCustomResp) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *GetMemberCustomResp) GetRegIp() string {
	if m != nil {
		return m.RegIp
	}
	return ""
}

func (m *GetMemberCustomResp) GetRegSrc() string {
	if m != nil {
		return m.RegSrc
	}
	return ""
}

func (m *GetMemberCustomResp) GetRegTime() int32 {
	if m != nil {
		return m.RegTime
	}
	return 0
}

func (m *GetMemberCustomResp) GetCpsId() int32 {
	if m != nil {
		return m.CpsId
	}
	return 0
}

func (m *GetMemberCustomResp) GetQq() string {
	if m != nil {
		return m.Qq
	}
	return ""
}

func (m *GetMemberCustomResp) GetNation() string {
	if m != nil {
		return m.Nation
	}
	return ""
}

func (m *GetMemberCustomResp) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *GetMemberCustomResp) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *GetMemberCustomResp) GetUpdateTime() int32 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *GetMemberCustomResp) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *GetMemberCustomResp) GetSalt() string {
	if m != nil {
		return m.Salt
	}
	return ""
}

func (m *GetMemberCustomResp) GetSeq() int32 {
	if m != nil {
		return m.Seq
	}
	return 0
}

type BatchGetMemberCustomResp struct {
	Result int32                  `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	List   []*GetMemberCustomResp `protobuf:"bytes,2,rep,name=list" json:"list,omitempty"`
}

func (m *BatchGetMemberCustomResp) Reset()                    { *m = BatchGetMemberCustomResp{} }
func (m *BatchGetMemberCustomResp) String() string            { return proto.CompactTextString(m) }
func (*BatchGetMemberCustomResp) ProtoMessage()               {}
func (*BatchGetMemberCustomResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *BatchGetMemberCustomResp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *BatchGetMemberCustomResp) GetList() []*GetMemberCustomResp {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*GetUserInfoRes)(nil), "pb.GetUserInfoRes")
	proto.RegisterType((*GetMemberDetailReq)(nil), "pb.GetMemberDetailReq")
	proto.RegisterType((*BatchGetMemberCustomReq)(nil), "pb.BatchGetMemberCustomReq")
	proto.RegisterType((*GetMemberCustomResp)(nil), "pb.GetMemberCustomResp")
	proto.RegisterType((*BatchGetMemberCustomResp)(nil), "pb.BatchGetMemberCustomResp")
}

func init() { proto.RegisterFile("userinfo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 666 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x94, 0x5d, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0x65, 0xd7, 0x4d, 0x9c, 0x69, 0x9a, 0x36, 0x9b, 0xaf, 0x4d, 0x79, 0x20, 0x8a, 0x78,
	0x88, 0x84, 0x54, 0x09, 0xb8, 0x01, 0x20, 0x55, 0x48, 0x94, 0x07, 0x0b, 0x9e, 0x2d, 0xc7, 0xde,
	0xa6, 0xab, 0xc6, 0xbb, 0xeb, 0xdd, 0x35, 0x6d, 0xcf, 0xc0, 0xad, 0xb8, 0x12, 0x17, 0x40, 0xb3,
	0xeb, 0x7c, 0x11, 0x84, 0xc4, 0xdb, 0xcc, 0xdf, 0xb3, 0x33, 0xd3, 0xff, 0xfc, 0x1a, 0xe8, 0xd5,
	0x86, 0x69, 0x2e, 0xee, 0xe4, 0xb5, 0xd2, 0xd2, 0x4a, 0x12, 0xaa, 0xe5, 0xfc, 0x57, 0x08, 0xbd,
	0x1b, 0x66, 0xbf, 0x19, 0xa6, 0x3f, 0x89, 0x3b, 0x99, 0x30, 0x43, 0xc6, 0xd0, 0xd2, 0xcc, 0xd4,
	0x6b, 0x4b, 0x83, 0x59, 0xb0, 0x38, 0x4d, 0x9a, 0x8c, 0x5c, 0xc2, 0x49, 0xcd, 0x0b, 0x1a, 0xce,
	0x82, 0xc5, 0x79, 0x82, 0x21, 0xe9, 0x41, 0x28, 0x04, 0x3d, 0x99, 0x05, 0x8b, 0x4e, 0x12, 0x0a,
	0x81, 0x79, 0x2d, 0x68, 0xe4, 0xf3, 0x5a, 0xe0, 0x8b, 0x15, 0x2f, 0xe8, 0xa9, 0x6b, 0x83, 0x21,
	0x2a, 0x52, 0x97, 0xb4, 0xe5, 0x15, 0xa9, 0x4b, 0x54, 0x58, 0x69, 0x68, 0xdb, 0x2b, 0xac, 0x34,
	0xd8, 0x45, 0x49, 0x1a, 0xfb, 0x2e, 0x4a, 0x62, 0x85, 0x92, 0x86, 0x76, 0x7c, 0x85, 0x92, 0xae,
	0x82, 0x5b, 0x0a, 0x4e, 0x08, 0xb9, 0xdb, 0x8c, 0x5b, 0x43, 0xcf, 0x7c, 0x05, 0xb7, 0x06, 0x15,
	0xc3, 0x9e, 0x68, 0xd7, 0x2b, 0x86, 0x3d, 0x11, 0x02, 0x11, 0xcf, 0xa5, 0xa0, 0xe7, 0xae, 0xaf,
	0x8b, 0xb1, 0x4a, 0x73, 0x45, 0x7b, 0x4e, 0xc2, 0x10, 0xab, 0xb4, 0xd1, 0x39, 0xbd, 0xf0, 0x55,
	0x18, 0xe3, 0x34, 0x6d, 0xe9, 0xe5, 0x2c, 0x58, 0x44, 0x49, 0xa8, 0xdd, 0xb4, 0x9c, 0x17, 0xb4,
	0xef, 0x7b, 0xe7, 0xde, 0x87, 0xaa, 0xa2, 0xc4, 0x6f, 0x5c, 0x55, 0xe4, 0x25, 0x9c, 0xd5, 0xaa,
	0xc8, 0x2c, 0x4b, 0x2d, 0x2f, 0x19, 0x1d, 0xb8, 0xa7, 0xe0, 0xa5, 0xaf, 0xbc, 0x64, 0xf3, 0x1f,
	0x01, 0x90, 0x1b, 0x66, 0x6f, 0x59, 0xb9, 0x64, 0xfa, 0x23, 0xb3, 0x19, 0x5f, 0x27, 0xac, 0xda,
	0x38, 0x1c, 0xec, 0x1c, 0xbe, 0x82, 0x58, 0xf0, 0xfc, 0x41, 0x64, 0x25, 0x73, 0xc6, 0x77, 0x92,
	0x6d, 0x4e, 0x5e, 0x40, 0x07, 0x0f, 0x9a, 0xba, 0x8f, 0xfe, 0x08, 0x31, 0x0a, 0x5f, 0xf0, 0xe3,
	0x10, 0x4e, 0x59, 0x99, 0xf1, 0x75, 0x73, 0x0d, 0x9f, 0xa0, 0xaa, 0xee, 0xa5, 0x60, 0xee, 0x24,
	0x9d, 0xc4, 0x27, 0x73, 0x0d, 0x93, 0xf7, 0x99, 0xcd, 0xef, 0xb7, 0x1b, 0x7d, 0xa8, 0x8d, 0x95,
	0x25, 0x6e, 0xf4, 0xca, 0x43, 0x93, 0x22, 0x35, 0x69, 0x99, 0x99, 0x07, 0xb7, 0x5c, 0x94, 0x74,
	0xeb, 0x06, 0x98, 0xdb, 0xcc, 0x3c, 0x90, 0x37, 0x10, 0x6b, 0x56, 0xa5, 0x6b, 0x6e, 0x2c, 0x0d,
	0x67, 0x27, 0x8b, 0xb3, 0xb7, 0xe3, 0x6b, 0xb5, 0xbc, 0x3e, 0xfe, 0x0b, 0x93, 0xb6, 0x66, 0xd5,
	0x67, 0x6e, 0xec, 0xfc, 0x67, 0x04, 0x83, 0xa3, 0x79, 0x46, 0xfd, 0x07, 0x7c, 0xc3, 0x3d, 0x6b,
	0x76, 0x08, 0x0e, 0xc1, 0x79, 0xe0, 0xd4, 0x1d, 0x88, 0x23, 0x88, 0x57, 0x5a, 0xd6, 0x2a, 0x3d,
	0xa4, 0x71, 0x04, 0xb1, 0x7c, 0x14, 0xa9, 0x96, 0xf2, 0x00, 0xc9, 0xfe, 0xc6, 0xbb, 0xb6, 0x6f,
	0xc0, 0x4a, 0x32, 0x85, 0xae, 0x93, 0x52, 0x63, 0x33, 0x5b, 0x1b, 0x47, 0x67, 0x83, 0x6b, 0x7f,
	0xe3, 0x69, 0x67, 0x4b, 0xec, 0x14, 0xba, 0x4e, 0xda, 0x54, 0xc3, 0x0e, 0xdd, 0x31, 0x00, 0x2f,
	0x98, 0xb0, 0xa9, 0x7d, 0x56, 0xac, 0x21, 0x16, 0x11, 0x9e, 0x42, 0xd7, 0xeb, 0xcd, 0x93, 0xee,
	0x11, 0xcb, 0xe7, 0xc7, 0x2c, 0xf7, 0xf6, 0x58, 0x1e, 0xa0, 0x71, 0xab, 0x94, 0xab, 0x86, 0x5d,
	0x87, 0xf3, 0x08, 0xda, 0x28, 0x22, 0xd1, 0x97, 0x7b, 0x44, 0x0f, 0xf1, 0x5e, 0x2b, 0x0f, 0xa7,
	0xc7, 0x18, 0xb9, 0x1e, 0x40, 0x2b, 0x57, 0x06, 0x2d, 0x22, 0x7f, 0xa2, 0x3d, 0xd8, 0xa2, 0xdd,
	0x87, 0x96, 0xc8, 0x2c, 0x97, 0x82, 0x0e, 0x9d, 0x16, 0xe0, 0xe4, 0x58, 0x69, 0xf9, 0x9d, 0x8b,
	0x9c, 0xd1, 0x91, 0x17, 0x15, 0xb9, 0x80, 0x28, 0xe7, 0xf6, 0x99, 0x8e, 0xbd, 0x90, 0x93, 0xc9,
	0xe1, 0xff, 0xc4, 0xc4, 0x8f, 0xad, 0x2d, 0x19, 0x43, 0xac, 0x32, 0x63, 0x1e, 0xa5, 0x2e, 0x28,
	0xf5, 0x4b, 0x62, 0x8e, 0x1d, 0x4c, 0xb6, 0xb6, 0x74, 0xea, 0x3b, 0x34, 0x3e, 0x54, 0xf4, 0x6a,
	0xe3, 0x43, 0x35, 0x4f, 0x81, 0xfe, 0x1d, 0xdc, 0x7f, 0x80, 0xf4, 0x1a, 0xa2, 0x3d, 0x4e, 0x27,
	0x07, 0x9c, 0xee, 0x9e, 0x27, 0xae, 0x68, 0xd9, 0x72, 0x3f, 0x94, 0xef, 0x7e, 0x07, 0x00, 0x00,
	0xff, 0xff, 0xcb, 0x5f, 0x94, 0xa7, 0x3a, 0x05, 0x00, 0x00,
}
