// Code generated by protoc-gen-go. DO NOT EDIT.
// source: xy_broadcast.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BroadcastReq struct {
	Reqsrc               string   `protobuf:"bytes,1,opt,name=reqsrc,proto3" json:"reqsrc,omitempty"`
	Appid                int32    `protobuf:"varint,2,opt,name=appid,proto3" json:"appid,omitempty"`
	Content              *Content `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadcastReq) Reset()         { *m = BroadcastReq{} }
func (m *BroadcastReq) String() string { return proto.CompactTextString(m) }
func (*BroadcastReq) ProtoMessage()    {}
func (*BroadcastReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_77d84a1296207a52, []int{0}
}

func (m *BroadcastReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastReq.Unmarshal(m, b)
}
func (m *BroadcastReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastReq.Marshal(b, m, deterministic)
}
func (m *BroadcastReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastReq.Merge(m, src)
}
func (m *BroadcastReq) XXX_Size() int {
	return xxx_messageInfo_BroadcastReq.Size(m)
}
func (m *BroadcastReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastReq.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastReq proto.InternalMessageInfo

func (m *BroadcastReq) GetReqsrc() string {
	if m != nil {
		return m.Reqsrc
	}
	return ""
}

func (m *BroadcastReq) GetAppid() int32 {
	if m != nil {
		return m.Appid
	}
	return 0
}

func (m *BroadcastReq) GetContent() *Content {
	if m != nil {
		return m.Content
	}
	return nil
}

type BroadcastRes struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadcastRes) Reset()         { *m = BroadcastRes{} }
func (m *BroadcastRes) String() string { return proto.CompactTextString(m) }
func (*BroadcastRes) ProtoMessage()    {}
func (*BroadcastRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_77d84a1296207a52, []int{1}
}

func (m *BroadcastRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastRes.Unmarshal(m, b)
}
func (m *BroadcastRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastRes.Marshal(b, m, deterministic)
}
func (m *BroadcastRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastRes.Merge(m, src)
}
func (m *BroadcastRes) XXX_Size() int {
	return xxx_messageInfo_BroadcastRes.Size(m)
}
func (m *BroadcastRes) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastRes.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastRes proto.InternalMessageInfo

func (m *BroadcastRes) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type Content struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Rid                  int32    `protobuf:"varint,2,opt,name=rid,proto3" json:"rid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Content) Reset()         { *m = Content{} }
func (m *Content) String() string { return proto.CompactTextString(m) }
func (*Content) ProtoMessage()    {}
func (*Content) Descriptor() ([]byte, []int) {
	return fileDescriptor_77d84a1296207a52, []int{2}
}

func (m *Content) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Content.Unmarshal(m, b)
}
func (m *Content) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Content.Marshal(b, m, deterministic)
}
func (m *Content) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Content.Merge(m, src)
}
func (m *Content) XXX_Size() int {
	return xxx_messageInfo_Content.Size(m)
}
func (m *Content) XXX_DiscardUnknown() {
	xxx_messageInfo_Content.DiscardUnknown(m)
}

var xxx_messageInfo_Content proto.InternalMessageInfo

func (m *Content) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Content) GetRid() int32 {
	if m != nil {
		return m.Rid
	}
	return 0
}

func init() {
	proto.RegisterType((*BroadcastReq)(nil), "pb.BroadcastReq")
	proto.RegisterType((*BroadcastRes)(nil), "pb.BroadcastRes")
	proto.RegisterType((*Content)(nil), "pb.Content")
}

func init() { proto.RegisterFile("xy_broadcast.proto", fileDescriptor_77d84a1296207a52) }

var fileDescriptor_77d84a1296207a52 = []byte{
	// 173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xaa, 0xa8, 0x8c, 0x4f,
	0x2a, 0xca, 0x4f, 0x4c, 0x49, 0x4e, 0x2c, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0x2a, 0x48, 0x52, 0x4a, 0xe6, 0xe2, 0x71, 0x82, 0x09, 0x07, 0xa5, 0x16, 0x0a, 0x89, 0x71, 0xb1,
	0x15, 0xa5, 0x16, 0x16, 0x17, 0x25, 0x4b, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x41, 0x79, 0x42,
	0x22, 0x5c, 0xac, 0x89, 0x05, 0x05, 0x99, 0x29, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x10,
	0x8e, 0x90, 0x2a, 0x17, 0x7b, 0x72, 0x7e, 0x5e, 0x49, 0x6a, 0x5e, 0x89, 0x04, 0xb3, 0x02, 0xa3,
	0x06, 0xb7, 0x11, 0xb7, 0x5e, 0x41, 0x92, 0x9e, 0x33, 0x44, 0x28, 0x08, 0x26, 0xa7, 0xa4, 0x86,
	0x62, 0x49, 0x31, 0xc4, 0x92, 0xe2, 0xd2, 0x9c, 0x12, 0xb0, 0x25, 0xac, 0x41, 0x50, 0x9e, 0x92,
	0x3e, 0x17, 0x3b, 0x54, 0xaf, 0x90, 0x10, 0x17, 0x4b, 0x49, 0x65, 0x41, 0x2a, 0xd4, 0x15, 0x60,
	0xb6, 0x90, 0x00, 0x17, 0x73, 0x11, 0xdc, 0x05, 0x20, 0x66, 0x12, 0x1b, 0xd8, 0x23, 0xc6, 0x80,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x0e, 0x83, 0x4a, 0x35, 0xde, 0x00, 0x00, 0x00,
}
