// Code generated by protoc-gen-go. DO NOT EDIT.
// source: checkwords.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CheckWordsRes struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Opt                  int32    `protobuf:"varint,2,opt,name=opt,proto3" json:"opt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckWordsRes) Reset()         { *m = CheckWordsRes{} }
func (m *CheckWordsRes) String() string { return proto.CompactTextString(m) }
func (*CheckWordsRes) ProtoMessage()    {}
func (*CheckWordsRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_54248a0773fe0166, []int{0}
}

func (m *CheckWordsRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckWordsRes.Unmarshal(m, b)
}
func (m *CheckWordsRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckWordsRes.Marshal(b, m, deterministic)
}
func (m *CheckWordsRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckWordsRes.Merge(m, src)
}
func (m *CheckWordsRes) XXX_Size() int {
	return xxx_messageInfo_CheckWordsRes.Size(m)
}
func (m *CheckWordsRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckWordsRes.DiscardUnknown(m)
}

var xxx_messageInfo_CheckWordsRes proto.InternalMessageInfo

func (m *CheckWordsRes) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *CheckWordsRes) GetOpt() int32 {
	if m != nil {
		return m.Opt
	}
	return 0
}

func init() {
	proto.RegisterType((*CheckWordsRes)(nil), "pb.CheckWordsRes")
}

func init() { proto.RegisterFile("checkwords.proto", fileDescriptor_54248a0773fe0166) }

var fileDescriptor_54248a0773fe0166 = []byte{
	// 95 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0xce, 0x48, 0x4d,
	0xce, 0x2e, 0xcf, 0x2f, 0x4a, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48,
	0x52, 0xb2, 0xe4, 0xe2, 0x75, 0x06, 0x89, 0x87, 0x83, 0xc4, 0x83, 0x52, 0x8b, 0x85, 0xc4, 0xb8,
	0xd8, 0x8a, 0x52, 0x8b, 0x4b, 0x73, 0x4a, 0x24, 0x18, 0x15, 0x18, 0x35, 0x58, 0x83, 0xa0, 0x3c,
	0x21, 0x01, 0x2e, 0xe6, 0xfc, 0x82, 0x12, 0x09, 0x26, 0xb0, 0x20, 0x88, 0x99, 0xc4, 0x06, 0x36,
	0xc5, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x7a, 0x2d, 0xb7, 0xec, 0x59, 0x00, 0x00, 0x00,
}
